services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PORT=5000
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db

  db:
    container_name: db-app
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /db-data:/var/lib/postgresql/data
    restart: unless-stopped
